### ISSUE TITLE
🚀 Deploy das resoluções no Github Pages

### ISSUE THREAD

**Issue by JoseCarlosNF** [JoseCarlosNF/resolucao-javascript-guanabara#2]
Deve ser criada a branch gh-pages, para deploy das resoluções no **Github Pages**.

**Comment by JoseCarlosNF** [comment]
Deploy realizado. Link de acesso https://josecarlosnf.github.io/resolucao-javascript-guanabara/

**Comment by JoneBulande** [comment]
É plausível o que fizeste, nice..
recomendo que disponibilizes o link github pages do repositório  na discrição
