### ISSUE TITLE
Erro no desafio 004

### ISSUE THREAD

**Issue by djonibourscheid** [JoseCarlosNF/resolucao-javascript-guanabara#5]
# Quando se um número com vírgula o código não entende e dá NaN

Colocando com vírgula:
![image](https://user-images.githubusercontent.com/62856037/79009791-bbf3f800-7b36-11ea-868a-55586c44882e.png)

Erro de NaN:
![image](https://user-images.githubusercontent.com/62856037/79009853-e34ac500-7b36-11ea-9cbc-63868715a118.png)
***
# Possível resolução
Pode fazer com que o site mande uma mensagem de erro fazendo com que o usuário digite novamente o valor mas dessa vez com um ponto, ou você verifica se há uma vírgula e muda para um ponto no script, assim não sendo preciso o usuário reenviar o valor

**Comment by JoseCarlosNF** [comment]
Olá @djonibourscheid notei que o erro se repete em outros desafios, e foram corrigidos. Obrigado pelo toque.
