### ISSUE TITLE
duvida sobre o readme

### ISSUE THREAD

**Issue by JoneBulande** [JoseCarlosNF/resolucao-javascript-guanabara#8]
Qual foi o procedimento para colocares os prints do site nas versões desktop e mobile nessas imagens, que simulam um leptop e smartphone?

**Comment by JoseCarlosNF** [comment]
Pegue as imagens, em png, e adicionei os prints. No caso, é uma única imagem com os dois dispositivos.

- [Imagem Mobile](https://www.nicepng.com/png/full/1008-10088000_search-png.png)
- [Imagem Desktop](https://www.nicepng.com/png/full/409-4094541_macbook-mockup-png.png)

**Comment by JoneBulande** [comment]
ok, obrigado aí.
